### ISSUE TITLE
[BUG] cannot install v1.2.0 in pnpm monorepo

### ISSUE THREAD

**Issue by dsvgl** [freddy38510/vue3-lazy-hydration#42]
Updating to latest 1.2.0 in my pnpm monorepo results in the following error after installing deps with `pnpm i`:

```
postinstall: sh: simple-git-hooks: command not found
```

<img width="647" alt="Bildschirmfoto 2022-09-23 um 20 31 02" src="https://user-images.githubusercontent.com/97700093/192034508-53db740c-24a3-4ffc-984b-6a97dcf71ccf.png">

**Comment by dsvgl** [comment]
works, thx!

**Comment by freddy38510** [comment]
Sorry, I thought these scripts would only run when installing dependencies from the library project itself. I guess I was wrong.

I'm glad it works now !
