### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by Baroshem** [freddy38510/vue3-lazy-hydration#52]
Hey Man,

Great work on this package. 

I wanted to implement similar thing for Nuxt 3 but as you have already done it for Vue 3, I decided not to copy your work but instead I have created a simple module for Nuxt that is a wrapper around your package so that the experience for Nuxt 3 users is a bit better (no configuration needed)

https://github.com/Baroshem/nuxt-lazy-hydrate

**Comment by Baroshem** [comment]
I will implement new configuration options like autoImportComposables that will auto import the composables that you have created and also some more when I will have some new ideas. If you have some ideas, do not hesitate to let me know :)

I will also share it on my social media to increae the traffic on your package :)

**Comment by freddy38510** [comment]
Hey!

That's great, I really appreciate that.

I will update the readme to add a link to your repository for Nuxt 3 users.

Automatic import of composables is a good idea. I guess that [import wrappers](https://github.com/freddy38510/vue3-lazy-hydration#import-wrappers) can also fit into it.

I will let you know if I have some ideas, I also planned to [deploy the demo](https://github.com/freddy38510/vue3-lazy-hydration/issues/38) (available in development). I think there could be improvements in the documentation.
